### ISSUE TITLE
Can I ask how you modified in the VTM correspondingly?

### ISSUE THREAD

**Issue by ShayleeZhang** [pinchieh/Two-phase-scheme-CNN#1]
Firstly, Thanks for your codes. I hava learned a lot from your work. 
But I still have some problems in how to use in VTM.
Can I know what your modified in VTM?
It is of great help to me. I will be appreciated.

**Comment by pinchieh** [comment]
First of all, before vtm starts to encode the frames, use cnn to write the information of these frames into files (in encmain.cpp, insert the code for executing the model python file, you can refer to here https://github.com/tianyili2017/HEVC-Complexity-Reduction?fbclid=IwAR1dLr7PNc1GfhBujEh2bkW4gLAOSYLDkdtJ5PQEhCkF5D4lHbZj95chsiA).
Next, read in the file just written when encode ctu, and limit the cu split depth in encmodectrl.cpp.
Finally, add the time spent on CNN prediction and the time spent on vtm encoding.

**Comment by qin-liming** [comment]
请问您有相关的发表的文章吗，想详细了解一下您的工作学习一下
